export const STARTED = "_STARTED";
export const SUCCEEDED = "_SUCCEEDED";
export const FAILED = "_FAILED";
export const ENDED = "_ENDED";

export const getStarted = state => state + STARTED;
export const getSucceeded = state => state + SUCCEEDED;
export const getFailed = state => state + FAILED;
export const getEnded = state => state + ENDED;

export const statusEnum = Object.freeze({
  DEFAULT: "default",
  ERROR: "error",
  SUCCESS: "success"
});

export const LOGIN_SET_DEFAULT = "LOGIN_SET_DEFAULT";
export const ACTIVE_USER = "ACTIVE_USER";
export const LOGIN_SUBMIT = "LOGIN_SUBMIT";
export const FORGOT_PASSWORD_SET_DEFAULT = "FORGOT_PASSWORD_SET_DEFAULT";
export const FORGOT_PASSWORD_SUBMIT = "FORGOT_PASSWORD_SUBMIT";
export const FORGOT_PASSWORD_RESET_SET_DEFAULT =
  "FORGOT_PASSWORD_RESET_SET_DEFAULT";
export const FORGOT_PASSWORD_RESET_SUBMIT = "FORGOT_PASSWORD_RESET_SUBMIT";
export const RESET_PASSWORD_DEFAULT = "RESET_PASSWORD_DEFAULT";
export const RESET_PASSWORD_SUBMIT = "RESET_PASSWORD_SUBMIT";
export const RESET_PASSWORD_SUBMIT_VALIDATION =
  "RESET_PASSWORD_SUBMIT_VALIDATION";
export const SIGN_UP_DEFAULT = "SIGN_UP_DEFAULT";
export const SIGN_UP_INITIALIZATION = "SIGN_UP_INITIALIZATION";
export const SIGN_UP_SUBMIT = "SIGN_UP_SUBMIT";
export const SIGN_UP_SUBMIT_VALIDATION = "SIGN_UP_SUBMIT_VALIDATION";
export const PROFILE_DEFAULT = "PROFILE_DEFAULT";
export const PROFILE_GET_USER_AND_SUBUSERS = "PROFILE_GET_USER_AND_SUBUSERS";
export const PROFILE_SUBMIT = "PROFILE_SUBMIT";
export const PROFILE_UPDATE_DEFAULT = "PROFILE_UPDATE_DEFAULT";
export const PROFILE_UPDATE_INITIALIZATION = "PROFILE_UPDATE_INITIALIZATION";
export const PROFILE_UPDATE_GET_USER = "PROFILE_UPDATE_GET_USER";
export const PROFILE_UPDATE_SUBMIT = "PROFILE_UPDATE_SUBMIT"; //USER_EDIT_SELECTED
export const PROFILE_EDIT_SELECTED = "PROFILE_EDIT_SELECTED";
export const PROFILE_LIST_RESET = "PROFILE_LIST_RESET";
export const PROFILE_OPTION_SELECTED = "PROFILE_OPTION_SELECTED";
export const CHANGE_PASSWORD_DEFAULT = "CHANGE_PASSWORD_DEFAULT";
export const CHANGE_PASSWORD_SUBMIT = "CHANGE_PASSWORD_SUBMIT";
export const ON_CHANGE_PROFILE_FORM = "ON_CHANGE_PROFILE_FORM";
export const CHANGE_PASSWORD_SUBMIT_VALIDATION =
  "CHANGE_PASSWORD_SUBMIT_VALIDATION";
export const SUB_USER_CREATE_DEFAULT = "SUB_USER_CREATE_DEFAULT";
export const SUB_USER_INITIALIZATION = "SUB_USER_INITIALIZATION";
export const SUB_USER_CREATE_SUBMIT = "SUB_USER_CREATE_SUBMIT";
export const SUB_USER_DELETE_SUBMIT = "SUB_USER_DELETE_SUBMIT";
export const RECIPE_MANAGEMENT_INITIALIZATION =
  "RECIPE_MANAGEMENT_INITIALIZATION";
export const RECIPE_MANAGEMENT_INGREDIENT_TOGGLE =
  "RECIPE_MANAGEMENT_INGREDIENT_TOGGLE";
export const RECIPE_MANAGEMENT_INGREDIENT_FILTER =
  "RECIPE_MANAGEMENT_INGREDIENT_FILTER";
export const RECIPE_MANAGEMENT_RECIPE_SELECT_TOGGLE =
  "RECIPE_MANAGEMENT_RECIPE_SELECT_TOGGLE";
export const RECIPE_MANAGEMENT_DELETE = "RECIPE_MANAGEMENT_DELETE";
export const RECIPE_INITIALIZATION = "RECIPE_INITIALIZATION";
export const RECIPE_ADD_ITEM = "RECIPE_ADD_ITEM";
export const RECIPE_EDIT_SELECTED = "RECIPE_EDIT_SELECTED";
export const RECIPE_SAVE_ITEM = "RECIPE_SAVE_ITEM";
export const RECIPE_DELETE = "RECIPE_DELETE";
export const RECIPE_SAVE = "RECIPE_SAVE";
export const RECIPE_CLEAR = "RECIPE_CLEAR";
export const SEARCH_INGREDIENTS = "SEARCH_INGREDIENTS";
export const SEARCH_RECIPES = "SEARCH_RECIPES";
export const ON_CHANGE_INGREDIENTFORM = "ON_CHANGE_INGREDIENTFORM";
export const ON_CHANGE_MYRECIPENTFORM = "ON_CHANGE_MYRECIPENTFORM";
export const INGREDIENT_OPTION_SELECTED = "INGREDIENT_OPTION_SELECTED";
export const GET_RECIPE = "GET_RECIPE";
export const RECIPE_CREATE_CUISINE = "RECIPE_CREATE_CUISINE";
export const RECIPE_CREATE_MEASUREMENT = "RECIPE_CREATE_MEASUREMENT";
export const RECIPE_MANAGEMENT_UPDATE_RATING =
  "RECIPE_MANAGEMENT_UPDATE_RATING";
export const RECIPE_MANAGEMENT_UPDATE_RANK = "RECIPE_MANAGEMENT_UPDATE_RANK";
export const GET_STOCKS = "GET_STOCKS";
export const GET_DETAIL_STOCKS = "GET_DETAIL_STOCKS";
export const GET_STOCK_INFO = "GET_STOCK_INFO";
export const SWIPE_STOCKS = "SWIPE_STOCKS";
export const DELETE_STOCK = "DELETE_STOCK";
export const ADD_STOCK = "ADD_STOCK";
export const RESET_STOCK_PAGE_MYDATA = "RESET_STOCK_PAGE_MYDATA";
export const ORDER_STOCK = "ORDER_STOCK";
export const SELECT_STOCK_ITEM = "SELECT_STOCK_ITEM";
export const SELECT_TIME_SELECTION = "SELECT_TIME_SELECTION";
export const GRAPH_INITIALIZATION = "GRAPH_INITIALIZATION";
export const UPDATE_BIG_GRAPH = "UPDATE_BIG_GRAPH";
export const ON_CHANGE_ANALYZEFORM = "ON_CHANGE_ANALYZEFORM";
export const ON_CHANGE_FACTOR_ANALYZEFORM = "ON_CHANGE_FACTOR_ANALYZEFORM";
export const ANALYZEPAGE_DATE_CHANGED = "ANALYZEPAGE_DATE_CHANGED";
export const RESET_ANALYZE_PAGE = "RESET_ANALYZE_PAGE";
export const ON_CHANGE_USER_ANALYZEFORM = "ON_CHANGE_USER_ANALYZEFORM";
export const TOGGLE_SEVERITY = "TOGGLE_SEVERITY";
export const GET_DASHBOARD_USERS = "GET_DASHBOARD_USERS";
export const RESET_VIEWSUMMARY_PAGE_MYDATA = "RESET_VIEWSUMMARY_PAGE_MYDATA";
export const GET_SYMPTOM_USERS = "GET_SYMPTOM_USERS";
export const GET_EDIT_SYMPTOM_USERS = "GET_EDIT_SYMPTOM_USERS";
export const SYMPTOM_USER_SELECTED = "SYMPTOM_USER_SELECTED";
export const SYMPTOM_CATEGORY_SELECTED = "SYMPTOM_CATEGORY_SELECTED";
export const EDIT_SYMPTOM_CATEGORY_SELECTED = "EDIT_SYMPTOM_CATEGORY_SELECTED";
export const CLEAR_SYMPTOM = "CLEAR_SYMPTOM";
export const SEARCH_SYMPTOM_OPTIONS = "SEARCH_SYMPTOM_OPTIONS";
export const EDIT_PAGE_SEARCH_SYMPTOM_OPTIONS =
  "EDIT_PAGE_SEARCH_SYMPTOM_OPTIONS";
export const ON_CHANGE_SYMPTOMFORM = "ON_CHANGE_SYMPTOMFORM";
export const SAVE_FOOD_AND_SYMPTOMS = "SAVE_FOOD_AND_SYMPTOMS";
export const SYPTOMS_ITEM_SELECT = "SYPTOMS_ITEM_SELECT";
export const SYMPTOMS_ITEM_UPDATE = "SYMPTOMS_ITEM_UPDATE";
export const RESET_INPUT_PAGE = "RESET_INPUT_PAGE";
export const RECIPE_ITEM_SELECT = "RECIPE_ITEM_SELECT";
export const SYMPTOMS_ITEM_DELETE = "SYMPTOMS_ITEM_DELETE";
export const SYMPTOM_DATE_CHANGED = "SYMPTOM_DATE_CHANGED";
export const EDIT_SYMPTOM_DATE_CHANGED = "EDIT_SYMPTOM_DATE_CHANGED";
export const SYMPTOM_DATE_RANGE_CHANGED = "SYMPTOM_DATE_RANGE_CHANGED";
export const GET_SYMPTOM_LIST = "GET_SYMPTOM_LIST";
export const SYMPTOM_SELECTED = "SYMPTOM_SELECTED";
export const SYMPTOM_DELETED = "SYMPTOM_DELETED";
export const SYMPTOM_OPTION_SELECTED = "SYMPTOM_OPTION_SELECTED";
export const CREATE_SYMPTOM = "CREATE_SYMPTOM";
export const INPUT_ADD_ITEM = "INPUT_ADD_ITEM";
export const UPDATE_SYMPTOM = "UPDATE_SYMPTOM";
export const ON_CHANGE_SYMPTOMEDITFORM = "ON_CHANGE_SYMPTOMEDITFORM";
export const ON_CHANGE_SEARCHFORM = "ON_CHANGE_SEARCHFORM";
export const SYMPTOM_SEARCH_DATE_CHANGED = "SYMPTOM_SEARCH_DATE_CHANGED";
export const RESET_EDIT_PAGE = "RESET_EDIT_PAGE";
export const ON_SAVE_PAGE_SYMPTOMEDITFORM = "ON_SAVE_PAGE_SYMPTOMEDITFORM";
export const EDITSYMPTOM_CHANGER_SEARCHFORM = "EDITSYMPTOM_CHANGER_SEARCHFORM";
export const EDIT_SYMPTOM_OPTION_SELECTED = "EDIT_SYMPTOM_OPTION_SELECTED";
export const SET_RECIPE_MANAGEMENT_FORM = "SET_RECIPE_MANAGEMENT_FORM";

export const PRODUCT_INITIALIZATION = "PRODUCT_INITIALIZATION";
export const PRODUCT_ADD_ITEM = "PRODUCT_ADD_ITEM";
export const PRODUCT_EDIT_SELECTED = "PRODUCT_EDIT_SELECTED";
export const PRODUCT_SAVE_ITEM = "PRODUCT_SAVE_ITEM";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const PRODUCT_SAVE = "PRODUCT_SAVE";
export const PRODUCT_CLEAR = "PRODUCT_CLEAR";
export const GET_PRODUCT = "GET_PRODUCT";
export const PRODUCT_CATEGORY_SELECTED = "PRODUCT_CATEGORY_SELECTED";
export const ON_CHANGE_PRODUCT = "ON_CHANGE_PRODUCT";
export const UPC_NOT_IN_PRODUCT = "UPC_NOT_IN_PRODUCT";
export const ON_CHANGE_INGREDIENTFORM_PRODUCT =
  "ON_CHANGE_INGREDIENTFORM_PRODUCT";
export const ON_SELECT_INGREDIENNAME_PRODUCT =
  "ON_SELECT_INGREDIENNAME_PRODUCT";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const SEARCH_BRANDS = "SEARCH_BRANDS";
export const SEARCH_PRODUCT_INGREDIENTS = "SEARCH_PRODUCT_INGREDIENTS";
export const MEAL_PLANNER_INITIALIZATION = "MEAL_PLANNER_INITIALIZATION";
export const ON_CHANGE_MEALPLANNERFORM = "ON_CHANGE_MEALPLANNERFORM";
export const ADD_NEW_FOOD_MEAL_PLANNER = "ADD_NEW_FOOD_MEAL_PLANNER";
export const MEAL_ITEM_CLICK_MEALPALNNER = "MEAL_ITEM_CLICK_MEALPALNNER";
export const MEAL_PLAN_SUMMARY_INITIALIZATION =
  "MEAL_PLAN_SUMMARY_INITIALIZATION";
export const MEAL_PLAN_SUMMARY_CHANGE_DATE = "MEAL_PLAN_SUMMARY_CHANGE_DATE";
export const EXTEND_MEAL_PLAN_SUMMARY = "EXTEND_MEAL_PLAN_SUMMARY";
export const ON_DROP_PLAN_SUMMARY = "ON_DROP_PLAN_SUMMARY";
export const MOVE_GRID_PLAN_SUMMARY = "MOVE_GRID_PLAN_SUMMARY";
export const DELETE_FOOD_MEAL_PLANNER = "DELETE_FOOD_MEAL_PLANNER";
export const ADD_UPDATE_MEAL_PLANNER = "ADD_UPDATE_MEAL_PLANNER";
export const LIST_COMBINE_MEAL_PLANNER = "LIST_COMBINE_MEAL_PLANNER";
export const TOGGLE_UNSAVE_MESSAGE = "TOGGLE_UNSAVE_MESSAGE";
export const FORUM_INSERT = "FORUM_INSERT";
export const FORUM_INITIALIZATION = "FORUM_INITIALIZATION";
export const FORUM_SINGLE_INITIALIZATION = "FORUM_SINGLE_INITIALIZATION";
export const ON_CHANGE_FORUM_FILTERS = "ON_CHANGE_FORUM_FILTERS";
export const RE_GET_FORUM_FILTERS = "RE_GET_FORUM_FILTERS";
export const FORUM_SELECT_FOR_EDIT_POST = "FORUM_SELECT_FOR_EDIT_POST";
export const FORUM_DO_ARCHIVE = "FORUM_DO_ARCHIVE";
export const FORUM_RELEVANT = "FORUM_RELEVANT";
export const FORUM_REMOVE_ARCHIVE = "FORUM_REMOVE_ARCHIVE";
export const FORUM_ON_CHANGE_STATE = "FORUM_ON_CHANGE_STATE";
export const FORUM_DELETE_POST = "FORUM_DELETE_POST";

function get_array(from, to) {
  let rlt = [];
  for (let i = from; i <= to; i++) rlt.push(i);
  return rlt;
}

export const SYMPTOM_UNITS = {
  SNS: {
    severity: get_array(-2, 2),
    label: []
  },
  Normal10: {
    severity: get_array(0, 10),
    label: []
  },
  GL: {
    severity: [],
    label: ["mmol/L", "mg/dL"]
  },
  BP: {
    severity: []
  },
  BT: {
    severity: [],
    label: ["celcius", "fahrenheit"]
  },
  BW: {
    severity: [],
    label: ["pound", "kg"]
  },
  BSC: {
    severity: get_array(1, 6)
  },
  None: {
    severity: get_array(0, 999),
    label: []
  }
};
